objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Dept Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EmployeeDetail__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>EmployeeDetail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EmployeeDetail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/empdetailinsert.cls
public with sharing class empdetailinsert
 {

public String name1 { get; set; }

    public String department{get;set;}
    public String email{get;set;}
    public String phone{get;set;}
    public Double salary{get;set;}
    public String id{get;set;}
  
    public PageReference recsave1() 
    {
    
    EmployeeDetail__c a = new EmployeeDetail__c(Name=name1,Department__c=department,Email__c=email,Phone__c=phone,salary__c=salary);
    
    insert a;
   
                
        return null;
        
    }
       
    List<EmployeeDetail__c> d;
  public  List<EmployeeDetail__c> getd()
     {
     
              if(d==null)
               d=[select id,Name,Department__c,Email__c,Salary__c,Phone__c from   EmployeeDetail__c];
               return d;  
     
     }


     

    
    
}