objects/Department123__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Burma</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dob__c</fullName>
        <label>Dob</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Department123</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department123</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/mytaskcontroller.cls
public class mytaskcontroller
{
  List<Department123__c>  dept;
  //Declaration list variable with Department123__c type
  public List<Department123__c> getDept()
  {
    if(dept==null)
     dept=[select id,Name,Dob__c,Country__c from Department123__c];
     //A List variable stores the records of Department123__c object because of List is Department123__c
        return dept;//it returns the Department123__c records to a PageBlock table .
  
  
  }




}