objects/Depart_ment__c.object
<CustomObject>
    <fields>
        <fullName>Depart_name__c</fullName>
        <label>Depart_name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Depart_ment</label>
    <nameField>
        <displayFormat>Appshark-{0000}</displayFormat>
        <label>DepartmentId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Emp_Details__c.object
<CustomObject>
    <fields>
        <fullName>Depart_ment__c</fullName>
        <label>Depart_ment</label>
        <referenceTo>Depart_ment__c</referenceTo>
        <relationshipLabel>Empdetails</relationshipLabel>
        <relationshipName>Empdetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>AssManager</fullName>
                </value>
                <value>
                    <fullName>TeamLead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Emp_Details</label>
    <nameField>
        <label>Emp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empdetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testdemoclass.cls
@istest
private class testdemoclass{
static testMethod void myUnitTest() {
Depart_ment__c dept=new Depart_ment__c();
dept.Depart_name__c  ='marketing';
insert dept;

Emp_Details__c edet=new Emp_Details__c();
edet.name='balaji';
edet.email__c='mbalaji105@gmail.com';
edet.role__c='teamlead';
edet.password__c='djsflk';
edet.Depart_ment__c=dept.id;
insert edet;

 Demo d = new Demo ();
 
 d.getstatus();
 d.geteid();
 d.dept = dept.id;
 d.emps = edet.id;
 d.get();
 d.getdeptname();
 d.getempname();
}

}