objects/SearchObject__c.object
<CustomObject>
    <fields>
        <fullName>Search__c</fullName>
        <label>Search</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>SearchObject</label>
    <nameField>
        <label>SearchObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SearchObject</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/acccon2.cls
public with sharing class acccon2 {
    List<SearchObject__c> acc;
        public acccon2(ApexPages.StandardController controller) {

    }
    public String accid{get; set;}
    
    public List<SearchObject__c> getlstaccounts()
    {
    acc=[Select id,name, Search__c from SearchObject__c];
    return acc;
    }
    
    public pagereference ref()
    {
    pagereference ref= new pagereference('/'+accid);
    ref.setredirect(true);
    return ref;
    }
    

}