objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Installment__c</fullName>
        <label>Installment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lastname__c</fullName>
        <label>Lastname</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestonstudentTriggers.cls
@isTest

private class TestonstudentTriggers {

 
    static testMethod void myUnitTest() {
        Student__c s = new Student__c();

        s.Name = 'Om Test';

        s.Lastname__c = 'LastName';
        s.Installment__c = 2000;
        s.Email__c = 'admin@shivasoft.in';
        
        
        try
        {

            insert s;

        }

        catch(System.DMLException e)

        {

            System.assert(e.getMessage().contains('Record already exist with same email Id'));

        }
       
    }

}